---
globals:
  root_path: git/analysis_datos/inper.mg.metab.1.3.6/
...

---
paths:
  data:
    root: /Dropbox/Brain/data/inper/mg_metab_136m_2023/
    folders:
      acquisitions: acq/
      processed: proc/
      results: res/
      dbs: db/
...

---
blocks:
  block:lmm:v2:db:
    load:
      tables: 
        db0:
          name  : ORP 2023 MG Metab 136m v2
          ext   : xlsx
          sheets:
            - wide
            - long
          var select: all
    save:   
      tables:
        data:
          name  : ORP 2023 MG Metab 136m
          ext   : xlsx   
  #
  block:lmm:
    load:
      tables: 
        db0:
          name  : ORP 2023 MG Metab 136m
          ext   : xlsx
          sheets:
            - long_format_db
          var select: all
    save:   
      tables:
        data:
          name  : ORP 2023 MG Metab 136m
          ext   : xlsx   
  #
  block:1:
    load:
      tables: 
        db0:
          name  : ORP 2023 MG Metab 136m
          ext   : xlsx
          sheets:
            - Crecimiento
            - join
          var select: all
    save:   
      tables:
        data:
          name  : ORP 2023 MG Metab 136m
          ext   : xlsx       
...

---
variables:
  tables: pass
  rename: pass
...
