---
title: "mg_metab_2023"
format: html
editor: visual
---

```{r}
library(dplyr)
library(knitr)
library(reticulate)
#library(lme4)
library(lmerTest)
library(magrittr)
library(kableExtra)
```

```{python}
import os
import numpy as np
import pandas as pd
```

```{python}
data_path = (f"~/Dropbox/Brain/data/inper/mg_metab_136m_2023/db/")
fname = "ORP 2023 MG Metab 136m v2.xlsx"
fname = os.path.expanduser(data_path) + fname
fname
```

```{python}
data = pd.read_excel(fname, sheet_name=['wide', 'long'])
wide = data['wide'].set_index('Exp_OBESO')
long = data['long'].set_index('Exp_OBESO')
#
df = long.join(wide, validate='m:1').reset_index()
```


```{r}
modelo_lmm <- lmer(MG_kg_PP ~ IMC + C_Abdomen +
                   IMC_preg_mat	+	Edad_mat	+	porc_MG_mat_1T + GP_mat_3T +
                   IMC_neon + C_Abdomen_neon + Inicio_AC + LME +
                   (1 + tiempo | Exp_OBESO) + (1 | Sexo), data = py$df, REML = TRUE)

summary(modelo_lmm)
```

```{r}
modelo_lmm1 <- lmer(C_Abdomen ~ IMC +
                   IMC_preg_mat	+	Edad_mat	+	porc_MG_mat_1T + GP_mat_3T +
                   IMC_neon + C_Abdomen_neon + Inicio_AC + LME +
                   (1 + tiempo | Exp_OBESO), data = py$df, REML = TRUE)
 
summary(modelo_lmm1)
```

```{r}
modelo_lmm2 <- lmer(C_Abdomen ~ IMC + porc_MG_PP +
                   IMC_preg_mat	+	Edad_mat	+	porc_MG_mat_1T + GP_mat_3T +
                   IMC_neon + Inicio_AC + LME +
                   (1 + tiempo | Exp_OBESO), data = py$df, REML = TRUE)
 
summary(modelo_lmm2)
```

```{r}
model.comparison <- anova(modelo_lmm1, modelo_lmm2)
 
summary(model.comparison)
```


```{python}
np.set_printoptions(suppress=True)
py_table = r.table.round(3)
py_table
```




```{r}
kable(py$py_table, 
      caption = "Resultados del modelo mixto de factores aleatorios",
      digits = 3,
      align = c("l", rep("c", 6)),
      col.names = c("Estimate", "SE", "df", "t value", "p-value"),
      space = "10em"
    )
```


```{r}

py$py_table %>%
  setNames(c( "Estimate", "SE", "df", "t value", "p-value")) %>%
  knitr::kable(booktabs=T) %>%
  kable_styling(font_size = 14,
                full_width = FALSE, position = "center", fixed_thead = TRUE,
                row_label_position = "right")
```





